# Generated by Django 4.2.6 on 2023-11-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trade_delete_crypto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='variant',
        ),
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
